### PR TITLE
Add replaceUrl parameter to certain router calls

### PR DESCRIPTION
**Pull request by Melonify**
Prevents history loops, where the user can't go back without being redirected again.

### CODE REVIEW

**Review by AnatoleAM — CHANGES_REQUESTED** [review]
This seems to break history and backward/forward-navigation for the emote list. 

Example: switching pages and then doing a backwards nav with the browser button takes you to the home page instead of the previous page. Likewise with searching and changing any search option

**Comment by AnatoleAM** [comment]
Can you also state where this "looping" occurs? Navigating around normally there doesn't seem to be

**Comment by Melonify** [comment]
As for where looping occurs, for example clicking the emotes tab from the top navbar, the user is first redirected to `/emotes`, however they are then closely after redirected to `/emotes?sortBy=popularity&page=0`. Attempting to navigate back to the original page the user was on before clicking the emotes tab, directs them to `/emotes` which then redirects to `/emotes?sortBy=popularity&page=0` once more, getting the user stuck in a loop.

Another location where this occurs is upon clicking a private emote from another user's page, the user gets first directed to the emote's page, but then shortly after, redirected to the emotes list, attempting to go back directs the user to the private emote's page which then redirects the user back to the emotes list.

**Review by AnatoleAM — APPROVED** [review]
Seems to function as expected, only issue I can see is that the search options don't update when navigating through history, however this is minor enough and can be fixed in a later PR

**Pull request merged**
