### PR TITLE
Added an option to select no paint

### PR DESCRIPTION
**Pull request by Excellify**
Adds a "No paint" selector if the user has any paints.
Sends a '0'*24 as a blank id to deselect all the others.
image

### CODE REVIEW

**Comment by AnatoleAM** [comment]
Huh I would expect the mongo driver on the API to throw a no documents error on this, but I guess that works

**Comment by Excellify** [comment]
> Huh I would expect the mongo driver on the API to throw a no documents error on this, but I guess that works

Yea, i don't know why it works tbh.

**Comment by AnatoleAM** [comment]
> > Huh I would expect the mongo driver on the API to throw a no documents error on this, but I guess that works
> 
> Yea, i don't know why it works tbh.

I was about to update the API to handle a zero-id just before you posted this, which I probably will do anyway since it is safer to handle it properly.

**Comment by Excellify** [comment]
> > > Huh I would expect the mongo driver on the API to throw a no documents error on this, but I guess that works
> > 
> > 
> > Yea, i don't know why it works tbh.
> 
> I was about to update the API to handle a zero-id just before you posted this, which I probably will do anyway since it is safer to handle it properly.

Just check if the id is 0 and skip straight to the un-select step?

**Comment by AnatoleAM** [comment]
> > > > Huh I would expect the mongo driver on the API to throw a no documents error on this, but I guess that works
> > > 
> > > 
> > > Yea, i don't know why it works tbh.
> > 
> > 
> > I was about to update the API to handle a zero-id just before you posted this, which I probably will do anyway since it is safer to handle it properly.
> 
> Just check if the id is 0 and skip straight to the un-select step?

That's pretty much how I did it, but it also considers any invalid ID as unselect. So in theory this could be changed to send "none" and it would work. But that's fine as it is

**Review by AnatoleAM — APPROVED** [review]

**Comment by Excellify** [comment]
> > > > > Huh I would expect the mongo driver on the API to throw a no documents error on this, but I guess that works
> > > > 
> > > > 
> > > > Yea, i don't know why it works tbh.
> > > 
> > > 
> > > I was about to update the API to handle a zero-id just before you posted this, which I probably will do anyway since it is safer to handle it properly.
> > 
> > 
> > Just check if the id is 0 and skip straight to the un-select step?
> 
> That's pretty much how I did it, but it also considers any invalid ID as unselect. So in theory this could be changed to send "none" and it would work. But that's fine as it is

Wouldn't "ObjectIDFromHex" throw on non hex value?

**Comment by AnatoleAM** [comment]
> > > > > > Huh I would expect the mongo driver on the API to throw a no documents error on this, but I guess that works
> > > > > 
> > > > > 
> > > > > Yea, i don't know why it works tbh.
> > > > 
> > > > 
> > > > I was about to update the API to handle a zero-id just before you posted this, which I probably will do anyway since it is safer to handle it properly.
> > > 
> > > 
> > > Just check if the id is 0 and skip straight to the un-select step?
> > 
> > 
> > That's pretty much how I did it, but it also considers any invalid ID as unselect. So in theory this could be changed to send "none" and it would work. But that's fine as it is
> 
> Wouldn't "ObjectIDFromHex" throw on non hex value?

The error isn't checked (golang has no exceptions) since it's known that the ID is valid when `IsValidObjectID()` is called

**Comment by Excellify** [comment]
> > > > > > > Huh I would expect the mongo driver on the API to throw a no documents error on this, but I guess that works
> > > > > > 
> > > > > > 
> > > > > > Yea, i don't know why it works tbh.
> > > > > 
> > > > > 
> > > > > I was about to update the API to handle a zero-id just before you posted this, which I probably will do anyway since it is safer to handle it properly.
> > > > 
> > > > 
> > > > Just check if the id is 0 and skip straight to the un-select step?
> > > 
> > > 
> > > That's pretty much how I did it, but it also considers any invalid ID as unselect. So in theory this could be changed to send "none" and it would work. But that's fine as it is
> > 
> > 
> > Wouldn't "ObjectIDFromHex" throw on non hex value?
> 
> The error isn't checked (golang has no exceptions) since it's known that the ID is valid when `IsValidObjectID()` is called

Saw your implementation now :+1:

**Pull request merged**
